import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// ESSE É O ARQUIVO PADRAO DO LAYOUT (RENDERIZADO PRIMEIRO PELO NEXTJS), ONDE TUDO O QUE COLOCAR AQUI VAI FICAR FIXO EM TODAS AS ROTAS

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gabriel Costa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
